
provers = [ "nunchaku-cvc4", "nunchaku-paradox", "nunchaku-kodkod", "nunchaku-smbc" ]

[nunchaku-cvc4]

cmd = "nunchaku --checks -s cvc4 -nc --timeout $timeout $file 2>&1"
binary_deps = [ "cvc4" ]
unsat = "UNSAT"
sat = "SAT:"
unknown = "TIMEOUT|UNKNOWN"
timeout = "TIMEOUT"

[nunchaku-smbc]

cmd = "nunchaku --checks -s smbc -nc --timeout $timeout $file 2>&1"
binary_deps = [ "smbc" ]
unsat = "UNSAT"
sat = "SAT :model"
unknown = "TIMEOUT|UNKNOWN"
timeout = "TIMEOUT"

[nunchaku-kodkod]

cmd = "nunchaku --checks -s kodkod -nc --timeout $timeout $file 2>&1"
binary_deps = [ "kodkod" ]
unsat = "UNSAT"
sat = "SAT:"
unknown = "TIMEOUT|UNKNOWN"
timeout = "TIMEOUT"

[nunchaku-paradox]

cmd = "nunchaku --checks -s paradox -nc --timeout $timeout $file 2>&1"
binary_deps = [ "paradox" ]
unsat = "UNSAT"
sat = "SAT:"
unknown = "TIMEOUT|UNKNOWN"
timeout = "TIMEOUT"

[test]

memory = 4000
timeout=10
problems = ".*.nun"
provers = [ "nunchaku-cvc4", "nunchaku-paradox", "nunchaku-kodkod", "nunchaku-smbc" ]
dir = [ "fixed_bugs", "tests" ]

