
[nunchaku]

cmd = "nunchaku --checks -s cvc4 -nc --timeout $timeout $file"
unsat = "UNSAT"
sat = "SAT:"
unknown = "TIMEOUT|UNKNOWN"
timeout = "TIMEOUT"

[test]

timeout=5
problems = ".*.nun"
provers = [ "nunchaku" ]
dir = [ "fixed_bugs", "tests" ]

