
timeout=5
prover = "nunchaku"
problems = ".*.nun"

[nunchaku]

cmd = "nunchaku --checks -s cvc4 -nc --timeout $timeout $file"
unsat = "UNSAT"
sat = "SAT:"
unknown = "TIMEOUT|UNKNOWN"
timeout = "TIMEOUT"

