
[nunchaku-paradox]

cmd = "nunchaku --checks -s paradox -nc --timeout $timeout $file 2>&1"
unsat = "UNSAT"
sat = "SAT:"
unknown = "TIMEOUT|UNKNOWN"
timeout = "TIMEOUT"

[test]

memory = 4000
timeout=10
problems = ".*.nun"
provers = [ "nunchaku-paradox" ]
dir = [ "fixed_bugs", "tests" ]

